---
title: "overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(listparser)
```

## Todos

* think about `.default` in `lcol_df()`
* `lcol_*()` should check for valid size of `.default`?

<!-- ## Overview -->

<!-- ```{r} -->
<!-- recordlist <- list( -->
<!--   list( -->
<!--     chr = "a", -->
<!--     int = 1 -->
<!--   ), -->
<!--   list( -->
<!--     chr = "b", -->
<!--     int = 2 -->
<!--   ) -->
<!-- ) -->

<!-- result <- tibblify(recordlist, col_specs = lcols(.default = lcol_guess(zap()))) -->
<!-- get_spec(result) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- recordlist <- list( -->
<!--   list( -->
<!--     df = list( -->
<!--       chr = "a", -->
<!--       int = 1 -->
<!--     ) -->
<!--   ), -->
<!--   list( -->
<!--     df = list( -->
<!--       chr = "b", -->
<!--       int = 2 -->
<!--     ) -->
<!--   ) -->
<!-- ) -->

<!-- result <- tibblify(recordlist, col_specs = lcols(.default = lcol_guess(zap()))) -->
<!-- get_spec(result) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- (result <- tibblify( -->
<!--   repurrrsive::discog %>%  -->
<!--     purrr::map("basic_information"), -->
<!--   lcols(.default = lcol_guess(zap()))) -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dplyr::glimpse(result$basic_information) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- get_spec(result) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- col_specs <- lcols( -->
<!--   lcol_df( -->
<!--     "df", -->
<!--     lcol_chr("chr", .default = NA_character_), -->
<!--     lcol_int("int") -->
<!--   ) -->
<!--   # lcol_int("int"), -->
<!--   # lcol_lst_flat("chr_lst") -->
<!-- ) -->

<!-- lcols( -->
<!--   .default = lcol_skip -->
<!-- ) -->

<!-- tibblify(recordlist, col_specs) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- col_specs <- lcols( -->
<!--   lcol_chr("chr", .default = NA_character_), -->
<!--   lcol_int("int"), -->
<!-- ) -->
<!-- tibblify(recordlist, col_specs) -->

<!-- col_specs <- lcols( -->
<!--   lcol_chr("chr"), -->
<!--   lcol_int("int"), -->
<!-- ) -->
<!-- tibblify(recordlist, col_specs) -->
<!-- ``` -->


<!-- ## Conversion: List to vec -->

<!-- ```{r} -->
<!-- purrr::map(recordlist, "chr", .default = NA_character_) %>%  -->
<!--   vec_unchop() -->

<!-- purrr::map(recordlist, "int", .default = integer()) %>%  -->
<!--   vec_unchop() -->

<!-- purrr::map(recordlist, "chr_lst") -->

<!-- vec_unchop(list(1:2, 3), ptype = integer()) -->

<!-- vec_unchop(list(Sys.time(), Sys.time()), ptype = Sys.time()) -->
<!-- vec_unchop(list(Sys.Date(), Sys.Date())) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- tibblify(recordlist, col_specs) -->
<!-- ``` -->
