# Generated by cpp11: do not edit by hand

tibblify_impl <- function(object_list, spec, path_ptr) {
  .Call(`_tibblify_tibblify_impl`, object_list, spec, path_ptr)
}

init_tibblify_path <- function() {
  .Call(`_tibblify_init_tibblify_path`)
}

get_path_data <- function(path_ptr) {
  .Call(`_tibblify_get_path_data`, path_ptr)
}
